updates.ignore = [
  # staying on sbt 1, because the Scala 2 community build is stuck on sbt 1,
  # and because we crossbuild to 2.12 anyway so it's not like the sbt 2 upgrade
  # would get us to a 3-only or even a 2.13+-only world
  { groupId = "org.scala-sbt", artifactId = "sbt", version = "2." }
]
